### PR TITLE
Update Human RL project template notebook

### PR DESCRIPTION
**Pull request by morteza**
This PR contains some minor fixes for the Human-RL project notebook.

### CODE REVIEW

**Comment by marius10p** [comment]
Thanks, can you please do the following and resubmit: 

1) edit -> clear all outputs
2) runtime -> factory reset

**Comment by marius10p** [comment]
I did not merge this in yet, are you going to submit a different pull request?

**Comment by morteza** [comment]
> I did not merge this in yet, are you going to submit a different pull request?

I just did. There is now only one PR with the outputs removed.

**Comment by morteza** [comment]
here are the commits including the new one: https://github.com/NeuromatchAcademy/course-content-dl/pull/357/commits

**Comment by marius10p** [comment]
Yeah, I think we're good on this PR. 

One more request, sorry:   could you please add another commit to this and say "skip ci" in the subject of the commit? You can just add a space somewhere and it will let you add a commit. This prevents some errors we've been seeing.

**Review by marius10p — APPROVED** [review]

**Pull request merged**
