### PR TITLE
W2D2 Tutorial 1 matched against style template.

### PR DESCRIPTION
**Pull request by DrAnoopKulkarni**
Initial version - checked against the template and all code cells are…running correctly.
All video links are updated and correct.
Objectives - this section needs to be updated by the CC

### CODE REVIEW

**Comment by cmurray7** [comment]
All authors match the DL Reviewers/Editors sheet
Issues: 
- [ ] Mismatch from NMA style guide: Imports should not be hidden. 
- [ ] I encountered `HTTPError: HTTP Error 403: rate limit exceeded` when requesting AlexNet from torch hub. This will likely be an intermittent failure (given that it passed the tests), but could cause problems day of. I will keep investigating to see what might help here. 
- [ ] Exercise 8 does not have any code or fill in the blank -- could this be renamed as a section? or have code with variables and placeholders with a to_remove cell containing the solution? 
- [ ] "click for solutions" link missing on 5.1, 5.2, 9.1, 9.2  -- other instructors did not have input fields /exercises for discussion questions, instead just posed the question in plain text. That is more in line with the NMA style, so consider changing to that format.

**Comment by spirosChv** [comment]
> All authors match the DL Reviewers/Editors sheet
> Issues:
> 
> * [ ]  Mismatch from NMA style guide: Imports should not be hidden.
> * [ ]  I encountered `HTTPError: HTTP Error 403: rate limit exceeded` when requesting AlexNet from torch hub. This will likely be an intermittent failure (given that it passed the tests), but could cause problems day of. I will keep investigating to see what might help here.
> * [ ]  Exercise 8 does not have any code or fill in the blank -- could this be renamed as a section? or have code with variables and placeholders with a to_remove cell containing the solution?
> * [ ]  "click for solutions" link missing on 5.1, 5.2, 9.1, 9.2  -- other instructors did not have input fields /exercises for discussion questions, instead just posed the question in plain text. That is more in line with the NMA style, so consider changing to that format.
> 
> Otherwise all the code exercises look good :)

@DrAnoopKulkarni can you address these comments?

**Comment by spirosChv** [comment]
Please do not merge before W2D1

**Comment by spirosChv** [comment]
Old slides from UPenn course, old videos`

fixes: cells with #to_remove explanation followed by a string, not commented out code.

ALERT

`Import Alexnet` error:

---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-33-aea0d8f0f3c5> in <module>()
      5 # Code from https://pytorch.org/hub/pytorch_vision_alexnet/
      6 
----> 7 alexnet = torch.hub.load('pytorch/vision:v0.6.0', 'alexnet', pretrained=True)
      8 
      9 

8 frames
/usr/lib/python3.7/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    647 class HTTPDefaultErrorHandler(BaseHandler):
    648     def http_error_default(self, req, fp, code, msg, hdrs):
--> 649         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    650 
    651 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: rate limit exceeded

**Comment by cmurray7** [comment]
> > All authors match the DL Reviewers/Editors sheet
> > Issues:
> > 
> > * [x]   Mismatch from NMA style guide: Imports should not be hidden.
> > * [x]   I encountered `HTTPError: HTTP Error 403: rate limit exceeded` when requesting AlexNet from torch hub. This will likely be an intermittent failure (given that it passed the tests), but could cause problems day of. I will keep investigating to see what might help here.
> > * [ ]   Exercise 8 does not have any code or fill in the blank -- could this be renamed as a section? or have code with variables and placeholders with a to_remove cell containing the solution?
> > * [x]   "click for solutions" link missing on 5.1, 5.2, 9.1, 9.2  -- other instructors did not have input fields /exercises for discussion questions, instead just posed the question in plain text. That is more in line with the NMA style, so consider changing to that format.
> > 
> > Otherwise all the code exercises look good :)
> 
> @DrAnoopKulkarni can you address these comments?

**Review by spirosChv — APPROVED** [review]

**Comment by spirosChv** [comment]
The code has a lot of stylistic format issues (PEP8 etc) but is good to go for prepod purposes.

**Pull request merged**
