### PR TITLE
fixed issues with colab

### PR DESCRIPTION
**Pull request by kvinehout**
I added pip install for N2V and limited W-net, N2V, and adding noise as helper functions.

### CODE REVIEW

**Comment by marius10p** [comment]
Thanks. Could you please add another commit to this and say "skip ci" in the subject of the commit? You can just add a space somewhere and it will let you add a commit. This prevents some errors we've been seeing.

**Review by marius10p — APPROVED** [review]

**Comment by marius10p** [comment]
Ugh, looks like this broke the book and it's very hard for us to debug why. Any idea what you might have added that is non-standard? @kvinehout

**Comment by kvinehout** [comment]
It looks like I made some commit to /code folder for the file with the same name. Not sure how this happened. The current version of notebook is under the computervision folder.

**Comment by marius10p** [comment]
Oh no, I should have checked, sorry. It's best to always start with a clean pull request, instead of continuing from the same branch. 

We can delete that file, but I'm not sure it would have broken the book, maybe @spirosChv knows.

**Comment by kvinehout** [comment]
I guess i dont know what you mean by the book. 
I install this package that is not standard within the colab.
!pip install n2v==0.3.0

**Comment by marius10p** [comment]
The book runs on CI for every pull request on this repo to make the jupyterbook: https://deeplearning.neuromatch.io/tutorials/intro.html 

It is not however very transparent when it errors, so we just try simplifying things as much as possible. The pip install should be fine though.

**Comment by kvinehout** [comment]
Maybe the space i put into the file with skip CI? Althought the file looks find on the github. I can just delete/reuplod the file to do the skip CI commit?

**Comment by marius10p** [comment]
Spaces should be fine. Let's wait a little bit, maybe @spirosChv figures it out.

**Pull request merged**
