### PR TITLE
Issue#798

### PR DESCRIPTION
**Pull request by GaganaB**

### CODE REVIEW

**Review by slashdottir — APPROVED** [review]
lgtm

**Comment by GaganaB** [comment]
@spirosChv Tagging you to keep you in the loop. Merge if it LGTY?

**Review by spirosChv — APPROVED** [review]

**Comment by spirosChv** [comment]
fixes https://github.com/NeuromatchAcademy/course-content-dl/issues/798

**Comment by slashdottir** [comment]
The same issue exists on W2D3_tutorial2.ipynb

I don't have permission to do a pull request, so someone else must do it

https://github.com/NeuromatchAcademy/course-content-dl/blob/main/tutorials/W2D3_ModernConvnets/W2D3_Tutorial2.ipynb

**Pull request merged**
