### PR TITLE
change folder names in tutorials

### PR DESCRIPTION
**Pull request by spirosChv**

### CODE REVIEW

**Comment by spirosChv** [comment]
Change folder names for README creation

**Comment by spirosChv** [comment]
@cmurray7 please check if everything is ok with the new names, and review the commit. Thanks

**Comment by cmurray7** [comment]
moves all look fine to me. 

 I am curious to see if there is a way to automatically run all the notebooks before submission so that we can still use the CI. Some notebooks require a GPU in order to run all the way through, so it isn't as simple as pulling the repo locally and then running a `jupyter nbconvert --execute --inplace --to notebook path.ipynb`.

**Review by cmurray7 — APPROVED** [review]
see comment above. We should let the content developers know that they need to use the 'skip ci' keywords to contribute to the repo from here on out.

**Comment by spirosChv** [comment]
> see comment above. We should let the content developers know that they need to use the 'skip ci' keywords to contribute to the repo from here on out.

I can re-run the notebooks. The CI should run to generate the student notebooks, check the exercises, etc. I have skipped it only to make the first commit

**Pull request merged**
