### PR TITLE
Updated with neuro 1 & 2 project templates

### PR DESCRIPTION
**Pull request by neurorishika**
Added "Vision with lost glasses" and "Moving Beyond Labels" templates (code and images). The template image has been linked to colabs on this repo after merging.

### CODE REVIEW

**Review by marius10p — CHANGES_REQUESTED** [review]
Thanks Rishika, looks good! I have a few requests: 

1) Please clear the outputs of the VisionWithLostGlass notebook. You can leave just essential figures, but please bring the file size to under 1 MB. 
2) There is a lot of code commented out in the same notebook, but I think that's important to make the blurry dataset, is it not? If it is, then please uncomment, if it's really "legacy", then please delete. 
3) Please remove the ideas/questions sections from both notebooks, since they are already in the project slide and we're trying to keep the two separate.

**Comment by neurorishika** [comment]
1. On it.
2. It's not needed to run here, but if the students want to generate processed datasets with different levels of blur/oterh forms of noise they can use the code. So should i keep it or not?
3. Sure

**Comment by marius10p** [comment]
Ok, move it to the bottom of the notebook then please and add some text at the top to clarify what that code is for. 

Also, please remove the "ideas" at the bottom of the Moving Beyond Labels notebook.

**Comment by neurorishika** [comment]
Done

**Review by marius10p — APPROVED** [review]
Thanks for making the changes.

**Pull request merged**
