### PR TITLE
updated dataset source for Twitter sentiment analysis template

### PR DESCRIPTION
**Pull request by dalia-nasr**

### CODE REVIEW

**Review by iamzoltan — CHANGES_REQUESTED** [review]
Looks like you need to restart kernel and clear all cells. What environment are you using?

**Comment by dalia-nasr** [comment]
> Looks like you need to restart kernel and clear all cells. What environment are you using?

Deal check the new commit. I'm editing and running the notebook in Google Colab.

**Comment by iamzoltan** [comment]
Its still pretty hard to see your changes. Can you run it locally?

**Comment by dalia-nasr** [comment]
> Its still pretty hard to see your changes. Can you run it locally?

Yes, it seems the changes are clear now.

**Review by iamzoltan — APPROVED** [review]
LGTM! Great work. if it passed our processing pipeline, we will include it in the next build

**Pull request merged**
