### PR TITLE
fix: minor broken code due to package versions

### PR DESCRIPTION
**Pull request by hanieh11**
librosa's newest version has changed some function names and variable calling, this branch fixes broken code regarding this issue.

### CODE REVIEW

**Review by iamzoltan — CHANGES_REQUESTED** [review]
Looks like to much oft he source file was changed. I cant view the diff on GH. How did you run the book? What environment are you using?

**Comment by hanieh11** [comment]
hi, actually only 2 lines of the code have been changed. in the first version I ran every cell of the notebook and since the output was included in both notebooks too much of the source code was considered to be changed. 
Two lines are:
`librosa.display.waveshow(y=y, sr=sample_rate);`
`S = librosa.feature.melspectrogram(y=y, sr=sr)`

**Comment by iamzoltan** [comment]
Yes, I understand. This is due to your environment. It is best to run jupyter notebook locally. Change the lines, and clear all cell and kernel before saving. Try that.

**Comment by hanieh11** [comment]
> Yes, I understand. This is due to your environment. It is best to run jupyter notebook locally. Change the lines, and clear all cell and kernel before saving. Try that.

In my second commit i only changed the lines without running it, therefore the notebook output must be the same as source code. But since you mentioned clearing all the outputs, in the 3rd commit the changes were made and all the outputs were cleared.

**Comment by iamzoltan** [comment]
addressed in #959

**Pull request closed without merging**
