### PR TITLE
FIX: Fixing memory limit exceeding in em_synapses.ipynb

### PR DESCRIPTION
**Pull request by MobinNesari81**
Hello. 
I hope you are doing well.
In this commit, I've solved the Google Colab Memory Limit Exceeding error by dividing the incoming package into smaller data chunks. I've tested both in Colab and my computer, and all things work very well. Please let me know if there are any other issues or ambiguities in my code or explanation.
I've also didn't add my name at the top of the file for notebook tester because I don't know if I should or not.
Sincerely,
M. Nesari

### CODE REVIEW

**Review by iamzoltan — CHANGES_REQUESTED** [review]
How are you saving the notebook? What environment are you using? Are you clearing the cells and kernel before saving? I cannot view the diff on GH

**Comment by GodPascal** [comment]
> How are you saving the notebook? What environment are you using? Are you clearing the cells and kernel before saving? I cannot view the diff on GH

By checking https://github.com/NeuromatchAcademy/course-content-dl/pull/955.patch you can see the diff (in an uglier way). I think the most important change Mobin has made is freeing the memory allocated to the downloaded file by changing `r = requests.get(url, allow_redirects=True, stream=True)` to `with requests.get(url, stream=True) as r:`.

**Comment by iamzoltan** [comment]
That sounds like a reasonable change. Please run the notebooks locally and make that small change. Then push your results. Dont forget to clear all cells and restart your kernel before saving. Otherwise we are including a lot of extra information that is unnecessary and makes it hard to review your changes.

**Comment by MobinNesari81** [comment]
Thank you @GodPascal for your explanation. As he said I declared a stream for downloading data to prevent memory limit exceeds error. I just talked with Marius and he said he would upload dataset splited files on OSF and when he send me download links I will update this file and run as you said and then resend it for you @iamzoltan . Is that ok?

**Comment by iamzoltan** [comment]
Sounds good to me.

**Comment by MobinNesari81** [comment]
Dear @iamzoltan,
I updated the notebook and push it here. I've also tested it and added new links. The notebook works perfectly.
Please let me know if there is any issue to solve.

**Review by iamzoltan — CHANGES_REQUESTED** [review]
hey @MobinNesari81,

It looks like you included .DS_Store in your commits. Can you please remove these

**Review by iamzoltan — COMMENTED** [review]
Will merge and test! thanks

**Review by iamzoltan — APPROVED** [review]
LGTM! I will run the processing again. Thanks @MobinNesari81

**Pull request merged**
